package de.ngloader.npcsystem.wrapper;

public enum EntityFlag {

	ENTITY_IS_ON_FIRE(EntityIndex.ENTITY_FLAG_0, 0x01),
	ENTITY_IS_CROUCHING(EntityIndex.ENTITY_FLAG_0, 0x02),
	ENTITY_IS_SPRINTING(EntityIndex.ENTITY_FLAG_0, 0x08),
	ENTITY_IS_SWIMMING(EntityIndex.ENTITY_FLAG_0, 0x10),
	ENTITY_IS_INVISIBLE(EntityIndex.ENTITY_FLAG_0, 0x20),
	ENTITY_IS_HAS_GLOWING_EFFECT(EntityIndex.ENTITY_FLAG_0, 0x40),
	ENTITY_IS_FLYING_WITH_A_ELYTRA(EntityIndex.ENTITY_FLAG_0, 0x80),

	ARROW_IS_CRITICAL(EntityIndex.ABSTRACT_ARROW_FLAG_8, 0x01),
	ARROW_IS_NOCLIP(EntityIndex.ABSTRACT_ARROW_FLAG_8, 0x02),

	LIVING_ENTITY_IS_HAND_ACTIVE(EntityIndex.LIVING_ENTITY_FLAG_8, 0x01),
	LIVING_ENTITY_ACTIVE_HAND(EntityIndex.LIVING_ENTITY_FLAG_8, 0x02),
	LIVING_ENTITY_IS_IN_RIPTIDE_SPIN_ATTACK(EntityIndex.LIVING_ENTITY_FLAG_8, 0x04),

	PLAYER_CAPE(EntityIndex.PLAYER_SKIN_PARTS_17, 0x01),
	PLAYER_JACKET(EntityIndex.PLAYER_SKIN_PARTS_17, 0x02),
	PLAYER_LEFT_SLEEVE(EntityIndex.PLAYER_SKIN_PARTS_17, 0x04),
	PLAYER_RIGHT_SLEEVE(EntityIndex.PLAYER_SKIN_PARTS_17, 0x08),
	PLAYER_LEFT_PANTS_LEG(EntityIndex.PLAYER_SKIN_PARTS_17, 0x10),
	PLAYER_RIGHT_PANTS_LEG(EntityIndex.PLAYER_SKIN_PARTS_17, 0x20),
	PLAYER_HAT(EntityIndex.PLAYER_SKIN_PARTS_17, 0x40),

	ARMORSTAND_IS_SMALL(EntityIndex.ARMORSTAND_FLAG_15, 0x01),
	ARMORSTAND_HAS_ARMS(EntityIndex.ARMORSTAND_FLAG_15, 0x04),
	ARMORSTAND_HAS_NO_BASEPLATE(EntityIndex.ARMORSTAND_FLAG_15, 0x08),
	ARMORSTAND_IS_MARKER(EntityIndex.ARMORSTAND_FLAG_15, 0x10),

	MOB_NO_AI(EntityIndex.MOB_FLAG_15, 0x01),
	MOB_IS_LEFT_HANDED(EntityIndex.MOB_FLAG_15, 0x02),
	MOB_IS_AGRESSIVE(EntityIndex.MOB_FLAG_15, 0x04),

	BAT_IS_HANGING(EntityIndex.BAT_FLAG_16, 0x01),

	HORSE_IS_TAME(EntityIndex.ABSTRACT_HORSE_FLAG_17, 0x02),
	HORSE_IS_SADDLED(EntityIndex.ABSTRACT_HORSE_FLAG_17, 0x04),
	HORSE_HAS_BRED(EntityIndex.ABSTRACT_HORSE_FLAG_17, 0x08),
	HORSE_IS_EATING(EntityIndex.ABSTRACT_HORSE_FLAG_17, 0x10),
	HORSE_IS_REARING(EntityIndex.ABSTRACT_HORSE_FLAG_17, 0x20),
	HORSE_IS_MOUTH_OPEN(EntityIndex.ABSTRACT_HORSE_FLAG_17, 0x40),

	BEE_IS_ANGRY(EntityIndex.BEE_FLAG_17, 0x02),
	BEE_HAS_STUNG(EntityIndex.BEE_FLAG_17, 0x04),
	BEE_HAS_NECTAR(EntityIndex.BEE_FLAG_17, 0x08),

	FOX_IS_SITTING(EntityIndex.FOX_FLAG_18, 0x01),
	FOX_IS_CROUCHING(EntityIndex.FOX_FLAG_18, 0x04),
	FOX_IS_INTERESTED(EntityIndex.FOX_FLAG_18, 0x08),
	FOX_IS_POUNCING(EntityIndex.FOX_FLAG_18, 0x10),
	FOX_IS_SLEEPING(EntityIndex.FOX_FLAG_18, 0x20),
	FOX_IS_FACEPLANTED(EntityIndex.FOX_FLAG_18, 0x40),
	FOX_IS_DEFENDING(EntityIndex.FOX_FLAG_18, 0x80),

	PANDA_IS_SNEEZING(EntityIndex.PANDA_FLAG_22, 0x02),
	PANDA_IS_ROLLING(EntityIndex.PANDA_FLAG_22, 0x04),
	PANDA_IS_SITTING(EntityIndex.PANDA_FLAG_22, 0x08),
	PANDA_IS_ON_BACK(EntityIndex.PANDA_FLAG_22, 0x10),

	SHEEP_COLOR_ID(EntityIndex.SHEEP_FLAG_17, 0x0F),
	SHEEP_IS_SHEARED(EntityIndex.SHEEP_FLAG_17, 0x10),

	TAMEABLE_IS_SITTING(EntityIndex.TAMEABLE_ANIMAL_FLAG_17, 0x01),
	TAMEABLE_IS_TAMED(EntityIndex.TAMEABLE_ANIMAL_FLAG_17, 0x04),

	IRON_GOLEM_IS_PLAYER_CREATED(EntityIndex.IRON_GOLEM_FLAG_16, 0x01),

	SNOW_GOLEM_HAS_NO_PUMPKIN_HAT(EntityIndex.SNOW_GOLEM_FLAG_16, 0x00),
	SNOW_GOLEM_HAS_PUMPKIN_HAT(EntityIndex.SNOW_GOLEM_FLAG_16, 0x10),

	BLAZE_IS_ON_FIRE(EntityIndex.BLAZE_FLAG_16, 0x01),

	VEX_IS_ATTACKING(EntityIndex.VEX_FLAG_16, 0x01),

	SPIDER_IS_CLIMBING(EntityIndex.SPIDER_FLAG_16, 0x01);

	private final int index;
	private final byte flag;

	private EntityFlag(EntityIndex index, int flag) {
		this.index = index.getIndex();
		this.flag = (byte) flag;
	}

	public int getIndex() {
		return this.index;
	}

	public byte getFlag() {
		return this.flag;
	}
}