package de.ngloader.ncpsystem.wrapper;

import net.minecraft.server.v1_16_R3.EntityTypes;
import net.minecraft.server.v1_16_R3.IRegistry;

public enum WrappedEntityId {

    AREA_EFFECT_CLOUD(EntityTypes.AREA_EFFECT_CLOUD),
    ARMOR_STAND(EntityTypes.ARMOR_STAND),
    ARROW(EntityTypes.ARROW),
    BAT(EntityTypes.BAT),
    BLAZE(EntityTypes.BLAZE),
    BOAT(EntityTypes.BOAT),
    CAT(EntityTypes.CAT),
    CAVE_SPIDER(EntityTypes.CAVE_SPIDER),
    CHICKEN(EntityTypes.CHICKEN),
    COD(EntityTypes.COD),
    COW(EntityTypes.COW),
    CREEPER(EntityTypes.CREEPER),
    DOLPHIN(EntityTypes.DOLPHIN),
    DONKEY(EntityTypes.DONKEY),
    DRAGON_FIREBALL(EntityTypes.DRAGON_FIREBALL),
    DROWNED(EntityTypes.DROWNED),
    ELDER_GUARDIAN(EntityTypes.ELDER_GUARDIAN),
    END_CRYSTAL(EntityTypes.END_CRYSTAL),
    ENDER_DRAGON(EntityTypes.ENDER_DRAGON),
    ENDERMAN(EntityTypes.ENDERMAN),
    ENDERMITE(EntityTypes.ENDERMITE),
    EVOKER(EntityTypes.EVOKER),
    EVOKER_FANGS(EntityTypes.EVOKER_FANGS),
    EXPERIENCE_ORB(EntityTypes.EXPERIENCE_ORB),
    EYE_OF_ENDER(EntityTypes.EYE_OF_ENDER),
    FALLING_BLOCK(EntityTypes.FALLING_BLOCK),
    FIREWORK_ROCKET(EntityTypes.FIREWORK_ROCKET),
    FOX(EntityTypes.FOX),
    GHAST(EntityTypes.GHAST),
    GIANT(EntityTypes.GIANT),
    GUARDIAN(EntityTypes.GUARDIAN),
    HORSE(EntityTypes.HORSE),
    HUSK(EntityTypes.HUSK),
    ILLUSIONER(EntityTypes.ILLUSIONER),
    IRON_GOLEM(EntityTypes.IRON_GOLEM),
    ITEM(EntityTypes.ITEM),
    ITEM_FRAME(EntityTypes.ITEM_FRAME),
    FIREBALL(EntityTypes.FIREBALL),
    LEASH_KNOT(EntityTypes.LEASH_KNOT),
    LIGHTNING_BOLT(EntityTypes.LIGHTNING_BOLT),
    LLAMA(EntityTypes.LLAMA),
    LLAMA_SPIT(EntityTypes.LLAMA_SPIT),
    MAGMA_CUBE(EntityTypes.MAGMA_CUBE),
    MINECART(EntityTypes.MINECART),
    CHEST_MINECART(EntityTypes.CHEST_MINECART),
    COMMAND_BLOCK_MINECART(EntityTypes.COMMAND_BLOCK_MINECART),
    FURNACE_MINECART(EntityTypes.FURNACE_MINECART),
    HOPPER_MINECART(EntityTypes.HOPPER_MINECART),
    SPAWNER_MINECART(EntityTypes.SPAWNER_MINECART),
    TNT_MINECART(EntityTypes.TNT_MINECART),
    MULE(EntityTypes.MULE),
    MOOSHROOM(EntityTypes.MOOSHROOM),
    OCELOT(EntityTypes.OCELOT),
    PAINTING(EntityTypes.PAINTING),
    PANDA(EntityTypes.PANDA),
    PARROT(EntityTypes.PARROT),
    PHANTOM(EntityTypes.PHANTOM),
    PIG(EntityTypes.PIG),
    PILLAGER(EntityTypes.PILLAGER),
    POLAR_BEAR(EntityTypes.POLAR_BEAR),
    TNT(EntityTypes.TNT),
    PUFFERFISH(EntityTypes.PUFFERFISH),
    RABBIT(EntityTypes.RABBIT),
    RAVAGER(EntityTypes.RAVAGER),
    SALMON(EntityTypes.SALMON),
    SHEEP(EntityTypes.SHEEP),
    SHULKER(EntityTypes.SHULKER),
    SHULKER_BULLET(EntityTypes.SHULKER_BULLET),
    SILVERFISH(EntityTypes.SILVERFISH),
    SKELETON(EntityTypes.SKELETON),
    SKELETON_HORSE(EntityTypes.SKELETON_HORSE),
    SLIME(EntityTypes.SLIME),
    SMALL_FIREBALL(EntityTypes.SMALL_FIREBALL),
    SNOW_GOLEM(EntityTypes.SNOW_GOLEM),
    SNOWBALL(EntityTypes.SNOWBALL),
    SPECTRAL_ARROW(EntityTypes.SPECTRAL_ARROW),
    SPIDER(EntityTypes.SPIDER),
    SQUID(EntityTypes.SQUID),
    STRAY(EntityTypes.STRAY),
    EGG(EntityTypes.EGG),
    ENDER_PEARL(EntityTypes.ENDER_PEARL),
    EXPERIENCE_BOTTLE(EntityTypes.EXPERIENCE_BOTTLE),
    POTION(EntityTypes.POTION),
    TRIDENT(EntityTypes.TRIDENT),
    TRADER_LLAMA(EntityTypes.TRADER_LLAMA),
    TROPICAL_FISH(EntityTypes.TROPICAL_FISH),
    TURTLE(EntityTypes.TURTLE),
    VEX(EntityTypes.VEX),
    VILLAGER(EntityTypes.VILLAGER),
    VINDICATOR(EntityTypes.VINDICATOR),
    WANDERING_TRADER(EntityTypes.WANDERING_TRADER),
    WITCH(EntityTypes.WITCH),
    WITHER(EntityTypes.WITHER),
    WITHER_SKELETON(EntityTypes.WITHER_SKELETON),
    WITHER_SKULL(EntityTypes.WITHER_SKULL),
    WOLF(EntityTypes.WOLF),
    ZOMBIE(EntityTypes.ZOMBIE),
    ZOMBIE_HORSE(EntityTypes.ZOMBIE_HORSE),
    ZOMBIE_VILLAGER(EntityTypes.ZOMBIE_VILLAGER),
    PLAYER(EntityTypes.PLAYER),
    FISHING_BOBBER(EntityTypes.FISHING_BOBBER);

    private final int id;

    private WrappedEntityId(EntityTypes<?> type) {
        this.id = IRegistry.ENTITY_TYPE.a(type);
    }

    public int getId() {
        return this.id;
    }
}
