name: Build

on:
  push:
    branches: ["**"]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
 
    - name: BuildTools cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository/org/spigotmc
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}

    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
 
    - name: Build
      run: |
        mvn clean package "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)--SNAPSHOT"
        mkdir dist
        mv target/npcsystem-*.jar ./dist

    - name: Create maven settings
      uses: s4u/maven-settings-action@v2.7.0
      with:
        servers: '[{ "id": "nexus", "username": "${{ secrets.NEXUS_DEPLOYMENT_NAME }}", "password": "${{ secrets.NEXUS_DEPLOYMENT }}" }]'
    - name: Publish to Nexus snapshots
      run: mvn -Daether.connector.basic.threads=1 -s ~/.m2/settings.xml deploy "-Drevision=${{ steps.short-sha.outputs.sha }}-SNAPSHOT"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Plugin
        path: dist/