name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6

    - name: BuildTools cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository/org/spigotmc
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
  
    - name: Create maven settings
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: '[{ "id": "nexus", "username": "${{ secrets.NEXUS_DEPLOYMENT_NAME }}", "password": "${{ secrets.NEXUS_DEPLOYMENT }}" }]'
    - name: Publish to Nexus snapshots
      run: mvn -Daether.connector.basic.threads=1 -s ~/.m2/settings.xml deploy "-Drevision=${{ steps.short-sha.outputs.sha }}-SNAPSHOT"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
